--- #YAML:1.0
name:                Captcha-reCAPTCHA
version:             0.92
abstract:            A Perl implementation of the reCAPTCHA API
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    HTML::Tiny:                    0.904
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Armstrong <andy@hexten.net>
